version: 1
genesis:
  app_state:
    staking:
      params:
        bond_denom: "space"
accounts:
  - name: alice
    coins:
      - 20000space
  - name: bob
    coins:
      - 10000space
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 5space
validators:
  - name: alice
    bonded: 10000space
