// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: filespacechain/filespacechain/hosting_offer.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HostingOffer struct {
	Id            uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string     `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	PricePerBlock types.Coin `protobuf:"bytes,3,opt,name=pricePerBlock,proto3" json:"pricePerBlock"`
	Creator       string     `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	InquiryId     uint64     `protobuf:"varint,5,opt,name=inquiryId,proto3" json:"inquiryId,omitempty"`
}

func (m *HostingOffer) Reset()         { *m = HostingOffer{} }
func (m *HostingOffer) String() string { return proto.CompactTextString(m) }
func (*HostingOffer) ProtoMessage()    {}
func (*HostingOffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b1ddde0ee789015, []int{0}
}
func (m *HostingOffer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HostingOffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HostingOffer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HostingOffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostingOffer.Merge(m, src)
}
func (m *HostingOffer) XXX_Size() int {
	return m.Size()
}
func (m *HostingOffer) XXX_DiscardUnknown() {
	xxx_messageInfo_HostingOffer.DiscardUnknown(m)
}

var xxx_messageInfo_HostingOffer proto.InternalMessageInfo

func (m *HostingOffer) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HostingOffer) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *HostingOffer) GetPricePerBlock() types.Coin {
	if m != nil {
		return m.PricePerBlock
	}
	return types.Coin{}
}

func (m *HostingOffer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *HostingOffer) GetInquiryId() uint64 {
	if m != nil {
		return m.InquiryId
	}
	return 0
}

func init() {
	proto.RegisterType((*HostingOffer)(nil), "filespacechain.filespacechain.HostingOffer")
}

func init() {
	proto.RegisterFile("filespacechain/filespacechain/hosting_offer.proto", fileDescriptor_7b1ddde0ee789015)
}

var fileDescriptor_7b1ddde0ee789015 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4e, 0x02, 0x31,
	0x14, 0x85, 0xa7, 0x88, 0x18, 0xea, 0xcf, 0x62, 0x62, 0xcc, 0x48, 0xb4, 0x12, 0x57, 0x6c, 0x6c,
	0x83, 0x6e, 0x5c, 0x63, 0x4c, 0x74, 0xa5, 0x99, 0xa5, 0x1b, 0xd3, 0x29, 0x65, 0xe6, 0x46, 0xe8,
	0x1d, 0xda, 0x62, 0xe4, 0x2d, 0x7c, 0x19, 0xdf, 0x81, 0x25, 0x4b, 0x57, 0xc6, 0xc0, 0x8b, 0x18,
	0x66, 0x30, 0x64, 0xd8, 0xf5, 0xb4, 0xf7, 0xf4, 0xbb, 0xf9, 0x68, 0x77, 0x00, 0x43, 0xed, 0x72,
	0xa9, 0xb4, 0xca, 0x24, 0x18, 0xb1, 0x15, 0x33, 0x74, 0x1e, 0x4c, 0xfa, 0x8a, 0x83, 0x81, 0xb6,
	0x3c, 0xb7, 0xe8, 0x31, 0x3c, 0xaf, 0xce, 0xf0, 0x6a, 0x6c, 0x1d, 0xa7, 0x98, 0x62, 0x31, 0x29,
	0x56, 0xa7, 0xb2, 0xd4, 0x62, 0x0a, 0xdd, 0x08, 0x9d, 0x48, 0xa4, 0xd3, 0xe2, 0xbd, 0x9b, 0x68,
	0x2f, 0xbb, 0x42, 0x21, 0x98, 0xf2, 0xfd, 0xf2, 0x8b, 0xd0, 0x83, 0x87, 0x12, 0xf6, 0xb4, 0x62,
	0x85, 0x47, 0xb4, 0x06, 0xfd, 0x88, 0xb4, 0x49, 0xa7, 0x1e, 0xd7, 0xa0, 0x1f, 0x9e, 0xd0, 0x86,
	0xd5, 0x29, 0xa0, 0x89, 0x6a, 0x6d, 0xd2, 0x69, 0xc6, 0xeb, 0x14, 0xde, 0xd3, 0xc3, 0xdc, 0x82,
	0xd2, 0xcf, 0xda, 0xf6, 0x86, 0xa8, 0xde, 0xa2, 0x9d, 0x36, 0xe9, 0xec, 0x5f, 0x9f, 0xf2, 0x12,
	0xc8, 0x57, 0x40, 0xbe, 0x06, 0xf2, 0x3b, 0x04, 0xd3, 0xab, 0xcf, 0x7e, 0x2e, 0x82, 0xb8, 0xda,
	0x0a, 0x23, 0xba, 0xa7, 0xac, 0x96, 0x1e, 0x6d, 0x54, 0x2f, 0xfe, 0xff, 0x8f, 0xe1, 0x19, 0x6d,
	0x82, 0x19, 0x4f, 0xc0, 0x4e, 0x1f, 0xfb, 0xd1, 0x6e, 0xb1, 0xcf, 0xe6, 0xa2, 0x17, 0xcf, 0x16,
	0x8c, 0xcc, 0x17, 0x8c, 0xfc, 0x2e, 0x18, 0xf9, 0x5c, 0xb2, 0x60, 0xbe, 0x64, 0xc1, 0xf7, 0x92,
	0x05, 0x2f, 0xb7, 0x29, 0xf8, 0x6c, 0x92, 0x70, 0x85, 0x23, 0x91, 0x49, 0xe3, 0xb2, 0xf1, 0x46,
	0xee, 0x55, 0x69, 0xf7, 0x63, 0x5b, 0xb7, 0x9f, 0xe6, 0xda, 0x25, 0x8d, 0x42, 0xc9, 0xcd, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x8f, 0x60, 0x1f, 0x9c, 0x01, 0x00, 0x00,
}

func (m *HostingOffer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HostingOffer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HostingOffer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InquiryId != 0 {
		i = encodeVarintHostingOffer(dAtA, i, uint64(m.InquiryId))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintHostingOffer(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.PricePerBlock.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintHostingOffer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Region) > 0 {
		i -= len(m.Region)
		copy(dAtA[i:], m.Region)
		i = encodeVarintHostingOffer(dAtA, i, uint64(len(m.Region)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintHostingOffer(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHostingOffer(dAtA []byte, offset int, v uint64) int {
	offset -= sovHostingOffer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HostingOffer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovHostingOffer(uint64(m.Id))
	}
	l = len(m.Region)
	if l > 0 {
		n += 1 + l + sovHostingOffer(uint64(l))
	}
	l = m.PricePerBlock.Size()
	n += 1 + l + sovHostingOffer(uint64(l))
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovHostingOffer(uint64(l))
	}
	if m.InquiryId != 0 {
		n += 1 + sovHostingOffer(uint64(m.InquiryId))
	}
	return n
}

func sovHostingOffer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHostingOffer(x uint64) (n int) {
	return sovHostingOffer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HostingOffer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHostingOffer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HostingOffer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HostingOffer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostingOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostingOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHostingOffer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHostingOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Region = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePerBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostingOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHostingOffer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHostingOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PricePerBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostingOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHostingOffer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHostingOffer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InquiryId", wireType)
			}
			m.InquiryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHostingOffer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InquiryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHostingOffer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHostingOffer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHostingOffer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHostingOffer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHostingOffer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHostingOffer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHostingOffer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHostingOffer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHostingOffer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHostingOffer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHostingOffer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHostingOffer = fmt.Errorf("proto: unexpected end of group")
)
