// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: filespacechain/filespacechain/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// Base price per byte per block for storage services
	BasePricePerBytePerBlock cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=base_price_per_byte_per_block,json=basePricePerBytePerBlock,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"base_price_per_byte_per_block"`
	// Minimum stake required for hosting providers
	MinProviderStake cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=min_provider_stake,json=minProviderStake,proto3,customtype=cosmossdk.io/math.Int" json:"min_provider_stake"`
	// Fraction of stake to slash for provider failures (0.0 to 1.0)
	SlashingFraction cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=slashing_fraction,json=slashingFraction,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slashing_fraction"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4d34b46c360ad71, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "filespacechain.filespacechain.Params")
}

func init() {
	proto.RegisterFile("filespacechain/filespacechain/params.proto", fileDescriptor_c4d34b46c360ad71)
}

var fileDescriptor_c4d34b46c360ad71 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x93, 0x7e, 0x50, 0xf8, 0x72, 0x6a, 0x83, 0x42, 0xa8, 0x34, 0x15, 0x05, 0x91, 0x82,
	0xc9, 0xc1, 0x8b, 0x78, 0x2c, 0x22, 0x88, 0x1e, 0x42, 0xbd, 0x79, 0x09, 0x93, 0xed, 0x36, 0x59,
	0xda, 0xdd, 0x59, 0x77, 0x57, 0x31, 0xaf, 0xe0, 0xc9, 0x47, 0xf0, 0x11, 0x7c, 0x02, 0xcf, 0x3d,
	0xf6, 0x28, 0x1e, 0x8a, 0xb4, 0x07, 0x7d, 0x0c, 0x49, 0x1a, 0x91, 0x56, 0x04, 0x2f, 0xbb, 0xff,
	0xd9, 0xe5, 0xf7, 0x63, 0x98, 0x71, 0xba, 0x43, 0x36, 0xa6, 0x5a, 0x02, 0xa1, 0x24, 0x03, 0x26,
	0xc2, 0xb5, 0x52, 0x82, 0x02, 0xae, 0x03, 0xa9, 0xd0, 0xa0, 0xdb, 0x5e, 0xfd, 0x0c, 0x56, 0xcb,
	0x56, 0x13, 0x38, 0x13, 0x18, 0x96, 0xe7, 0x92, 0x68, 0x6d, 0xa4, 0x98, 0x62, 0x19, 0xc3, 0x22,
	0x2d, 0x5f, 0x77, 0x9e, 0x6b, 0x4e, 0x3d, 0x2a, 0xc5, 0xee, 0xc0, 0x69, 0x27, 0xa0, 0x69, 0x2c,
	0x15, 0x23, 0x34, 0x96, 0x54, 0xc5, 0x49, 0x6e, 0xaa, 0x30, 0x46, 0x32, 0xf2, 0xec, 0x6d, 0x7b,
	0xff, 0x7f, 0x6f, 0x77, 0x32, 0xeb, 0x58, 0xaf, 0xb3, 0xce, 0x16, 0x41, 0xcd, 0x51, 0xeb, 0xc1,
	0x28, 0x60, 0x18, 0x72, 0x30, 0x59, 0x70, 0x41, 0x53, 0x20, 0xf9, 0x09, 0x25, 0x7d, 0xaf, 0x30,
	0x45, 0x85, 0x28, 0xa2, 0xaa, 0x97, 0x9b, 0xf2, 0x2a, 0x24, 0xee, 0xb9, 0xe3, 0x72, 0x26, 0x62,
	0xa9, 0xf0, 0x96, 0x0d, 0xa8, 0x8a, 0xb5, 0x81, 0x11, 0xf5, 0x6a, 0xa5, 0xba, 0x5d, 0xa9, 0x37,
	0x7f, 0xaa, 0xcf, 0x84, 0xe9, 0x37, 0x38, 0x13, 0x51, 0xc5, 0x5d, 0x16, 0x98, 0x1b, 0x39, 0x4d,
	0x3d, 0x06, 0x9d, 0x31, 0x91, 0xc6, 0x43, 0x05, 0xc4, 0x30, 0x14, 0xde, 0xbf, 0xbf, 0xb7, 0xd9,
	0xf8, 0xa2, 0x4f, 0x2b, 0xf8, 0x38, 0xfc, 0x78, 0xec, 0xd8, 0xf7, 0xef, 0x4f, 0xdd, 0xbd, 0xb5,
	0xe9, 0xdf, 0xad, 0xaf, 0x63, 0x39, 0xb5, 0x5e, 0x7f, 0x32, 0xf7, 0xed, 0xe9, 0xdc, 0xb7, 0xdf,
	0xe6, 0xbe, 0xfd, 0xb0, 0xf0, 0xad, 0xe9, 0xc2, 0xb7, 0x5e, 0x16, 0xbe, 0x75, 0x75, 0x94, 0x32,
	0x93, 0xdd, 0x24, 0x01, 0x41, 0x1e, 0x66, 0x20, 0x74, 0x76, 0xfd, 0xad, 0x38, 0xf8, 0x45, 0x6a,
	0x72, 0x49, 0x75, 0x52, 0x2f, 0x77, 0x73, 0xf8, 0x19, 0x00, 0x00, 0xff, 0xff, 0x17, 0x4d, 0x09,
	0xf7, 0x11, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.BasePricePerBytePerBlock.Equal(that1.BasePricePerBytePerBlock) {
		return false
	}
	if !this.MinProviderStake.Equal(that1.MinProviderStake) {
		return false
	}
	if !this.SlashingFraction.Equal(that1.SlashingFraction) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SlashingFraction.Size()
		i -= size
		if _, err := m.SlashingFraction.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinProviderStake.Size()
		i -= size
		if _, err := m.MinProviderStake.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.BasePricePerBytePerBlock.Size()
		i -= size
		if _, err := m.BasePricePerBytePerBlock.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BasePricePerBytePerBlock.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinProviderStake.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SlashingFraction.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasePricePerBytePerBlock", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BasePricePerBytePerBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinProviderStake", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinProviderStake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashingFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashingFraction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
