// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package filespacechain

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_FileEntry           protoreflect.MessageDescriptor
	fd_FileEntry_id        protoreflect.FieldDescriptor
	fd_FileEntry_cid       protoreflect.FieldDescriptor
	fd_FileEntry_rootCid   protoreflect.FieldDescriptor
	fd_FileEntry_parentCid protoreflect.FieldDescriptor
	fd_FileEntry_metaData  protoreflect.FieldDescriptor
	fd_FileEntry_fileSize  protoreflect.FieldDescriptor
	fd_FileEntry_creator   protoreflect.FieldDescriptor
)

func init() {
	file_filespacechain_filespacechain_file_entry_proto_init()
	md_FileEntry = File_filespacechain_filespacechain_file_entry_proto.Messages().ByName("FileEntry")
	fd_FileEntry_id = md_FileEntry.Fields().ByName("id")
	fd_FileEntry_cid = md_FileEntry.Fields().ByName("cid")
	fd_FileEntry_rootCid = md_FileEntry.Fields().ByName("rootCid")
	fd_FileEntry_parentCid = md_FileEntry.Fields().ByName("parentCid")
	fd_FileEntry_metaData = md_FileEntry.Fields().ByName("metaData")
	fd_FileEntry_fileSize = md_FileEntry.Fields().ByName("fileSize")
	fd_FileEntry_creator = md_FileEntry.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_FileEntry)(nil)

type fastReflection_FileEntry FileEntry

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	return (*fastReflection_FileEntry)(x)
}

func (x *FileEntry) slowProtoReflect() protoreflect.Message {
	mi := &file_filespacechain_filespacechain_file_entry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_FileEntry_messageType fastReflection_FileEntry_messageType
var _ protoreflect.MessageType = fastReflection_FileEntry_messageType{}

type fastReflection_FileEntry_messageType struct{}

func (x fastReflection_FileEntry_messageType) Zero() protoreflect.Message {
	return (*fastReflection_FileEntry)(nil)
}
func (x fastReflection_FileEntry_messageType) New() protoreflect.Message {
	return new(fastReflection_FileEntry)
}
func (x fastReflection_FileEntry_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_FileEntry
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_FileEntry) Descriptor() protoreflect.MessageDescriptor {
	return md_FileEntry
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_FileEntry) Type() protoreflect.MessageType {
	return _fastReflection_FileEntry_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_FileEntry) New() protoreflect.Message {
	return new(fastReflection_FileEntry)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_FileEntry) Interface() protoreflect.ProtoMessage {
	return (*FileEntry)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_FileEntry) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_FileEntry_id, value) {
			return
		}
	}
	if x.Cid != "" {
		value := protoreflect.ValueOfString(x.Cid)
		if !f(fd_FileEntry_cid, value) {
			return
		}
	}
	if x.RootCid != "" {
		value := protoreflect.ValueOfString(x.RootCid)
		if !f(fd_FileEntry_rootCid, value) {
			return
		}
	}
	if x.ParentCid != "" {
		value := protoreflect.ValueOfString(x.ParentCid)
		if !f(fd_FileEntry_parentCid, value) {
			return
		}
	}
	if x.MetaData != "" {
		value := protoreflect.ValueOfString(x.MetaData)
		if !f(fd_FileEntry_metaData, value) {
			return
		}
	}
	if x.FileSize != uint64(0) {
		value := protoreflect.ValueOfUint64(x.FileSize)
		if !f(fd_FileEntry_fileSize, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_FileEntry_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_FileEntry) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "filespacechain.filespacechain.FileEntry.id":
		return x.Id != uint64(0)
	case "filespacechain.filespacechain.FileEntry.cid":
		return x.Cid != ""
	case "filespacechain.filespacechain.FileEntry.rootCid":
		return x.RootCid != ""
	case "filespacechain.filespacechain.FileEntry.parentCid":
		return x.ParentCid != ""
	case "filespacechain.filespacechain.FileEntry.metaData":
		return x.MetaData != ""
	case "filespacechain.filespacechain.FileEntry.fileSize":
		return x.FileSize != uint64(0)
	case "filespacechain.filespacechain.FileEntry.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.FileEntry"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.FileEntry does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_FileEntry) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "filespacechain.filespacechain.FileEntry.id":
		x.Id = uint64(0)
	case "filespacechain.filespacechain.FileEntry.cid":
		x.Cid = ""
	case "filespacechain.filespacechain.FileEntry.rootCid":
		x.RootCid = ""
	case "filespacechain.filespacechain.FileEntry.parentCid":
		x.ParentCid = ""
	case "filespacechain.filespacechain.FileEntry.metaData":
		x.MetaData = ""
	case "filespacechain.filespacechain.FileEntry.fileSize":
		x.FileSize = uint64(0)
	case "filespacechain.filespacechain.FileEntry.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.FileEntry"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.FileEntry does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_FileEntry) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "filespacechain.filespacechain.FileEntry.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "filespacechain.filespacechain.FileEntry.cid":
		value := x.Cid
		return protoreflect.ValueOfString(value)
	case "filespacechain.filespacechain.FileEntry.rootCid":
		value := x.RootCid
		return protoreflect.ValueOfString(value)
	case "filespacechain.filespacechain.FileEntry.parentCid":
		value := x.ParentCid
		return protoreflect.ValueOfString(value)
	case "filespacechain.filespacechain.FileEntry.metaData":
		value := x.MetaData
		return protoreflect.ValueOfString(value)
	case "filespacechain.filespacechain.FileEntry.fileSize":
		value := x.FileSize
		return protoreflect.ValueOfUint64(value)
	case "filespacechain.filespacechain.FileEntry.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.FileEntry"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.FileEntry does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_FileEntry) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "filespacechain.filespacechain.FileEntry.id":
		x.Id = value.Uint()
	case "filespacechain.filespacechain.FileEntry.cid":
		x.Cid = value.Interface().(string)
	case "filespacechain.filespacechain.FileEntry.rootCid":
		x.RootCid = value.Interface().(string)
	case "filespacechain.filespacechain.FileEntry.parentCid":
		x.ParentCid = value.Interface().(string)
	case "filespacechain.filespacechain.FileEntry.metaData":
		x.MetaData = value.Interface().(string)
	case "filespacechain.filespacechain.FileEntry.fileSize":
		x.FileSize = value.Uint()
	case "filespacechain.filespacechain.FileEntry.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.FileEntry"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.FileEntry does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_FileEntry) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "filespacechain.filespacechain.FileEntry.id":
		panic(fmt.Errorf("field id of message filespacechain.filespacechain.FileEntry is not mutable"))
	case "filespacechain.filespacechain.FileEntry.cid":
		panic(fmt.Errorf("field cid of message filespacechain.filespacechain.FileEntry is not mutable"))
	case "filespacechain.filespacechain.FileEntry.rootCid":
		panic(fmt.Errorf("field rootCid of message filespacechain.filespacechain.FileEntry is not mutable"))
	case "filespacechain.filespacechain.FileEntry.parentCid":
		panic(fmt.Errorf("field parentCid of message filespacechain.filespacechain.FileEntry is not mutable"))
	case "filespacechain.filespacechain.FileEntry.metaData":
		panic(fmt.Errorf("field metaData of message filespacechain.filespacechain.FileEntry is not mutable"))
	case "filespacechain.filespacechain.FileEntry.fileSize":
		panic(fmt.Errorf("field fileSize of message filespacechain.filespacechain.FileEntry is not mutable"))
	case "filespacechain.filespacechain.FileEntry.creator":
		panic(fmt.Errorf("field creator of message filespacechain.filespacechain.FileEntry is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.FileEntry"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.FileEntry does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_FileEntry) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "filespacechain.filespacechain.FileEntry.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "filespacechain.filespacechain.FileEntry.cid":
		return protoreflect.ValueOfString("")
	case "filespacechain.filespacechain.FileEntry.rootCid":
		return protoreflect.ValueOfString("")
	case "filespacechain.filespacechain.FileEntry.parentCid":
		return protoreflect.ValueOfString("")
	case "filespacechain.filespacechain.FileEntry.metaData":
		return protoreflect.ValueOfString("")
	case "filespacechain.filespacechain.FileEntry.fileSize":
		return protoreflect.ValueOfUint64(uint64(0))
	case "filespacechain.filespacechain.FileEntry.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.FileEntry"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.FileEntry does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_FileEntry) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in filespacechain.filespacechain.FileEntry", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_FileEntry) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_FileEntry) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_FileEntry) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_FileEntry) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*FileEntry)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Cid)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.RootCid)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ParentCid)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MetaData)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.FileSize != 0 {
			n += 1 + runtime.Sov(uint64(x.FileSize))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*FileEntry)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x3a
		}
		if x.FileSize != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.FileSize))
			i--
			dAtA[i] = 0x30
		}
		if len(x.MetaData) > 0 {
			i -= len(x.MetaData)
			copy(dAtA[i:], x.MetaData)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MetaData)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.ParentCid) > 0 {
			i -= len(x.ParentCid)
			copy(dAtA[i:], x.ParentCid)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ParentCid)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.RootCid) > 0 {
			i -= len(x.RootCid)
			copy(dAtA[i:], x.RootCid)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.RootCid)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Cid) > 0 {
			i -= len(x.Cid)
			copy(dAtA[i:], x.Cid)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Cid)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*FileEntry)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: FileEntry: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: FileEntry: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Cid = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RootCid", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.RootCid = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ParentCid", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ParentCid = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MetaData", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MetaData = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
				}
				x.FileSize = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.FileSize |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: filespacechain/filespacechain/file_entry.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid       string `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	RootCid   string `protobuf:"bytes,3,opt,name=rootCid,proto3" json:"rootCid,omitempty"`
	ParentCid string `protobuf:"bytes,4,opt,name=parentCid,proto3" json:"parentCid,omitempty"`
	MetaData  string `protobuf:"bytes,5,opt,name=metaData,proto3" json:"metaData,omitempty"`
	FileSize  uint64 `protobuf:"varint,6,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	Creator   string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filespacechain_filespacechain_file_entry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_filespacechain_filespacechain_file_entry_proto_rawDescGZIP(), []int{0}
}

func (x *FileEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileEntry) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *FileEntry) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

func (x *FileEntry) GetParentCid() string {
	if x != nil {
		return x.ParentCid
	}
	return ""
}

func (x *FileEntry) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *FileEntry) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileEntry) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_filespacechain_filespacechain_file_entry_proto protoreflect.FileDescriptor

var file_filespacechain_filespacechain_file_entry_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x22,
	0xb7, 0x01, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x43, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x43, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0xf8, 0x01, 0x0a, 0x21, 0x63, 0x6f,
	0x6d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42,
	0x0e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0xa2, 0x02, 0x03, 0x46, 0x46, 0x58, 0xaa, 0x02, 0x1d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xca, 0x02, 0x1d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xe2, 0x02, 0x29, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x1e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filespacechain_filespacechain_file_entry_proto_rawDescOnce sync.Once
	file_filespacechain_filespacechain_file_entry_proto_rawDescData = file_filespacechain_filespacechain_file_entry_proto_rawDesc
)

func file_filespacechain_filespacechain_file_entry_proto_rawDescGZIP() []byte {
	file_filespacechain_filespacechain_file_entry_proto_rawDescOnce.Do(func() {
		file_filespacechain_filespacechain_file_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_filespacechain_filespacechain_file_entry_proto_rawDescData)
	})
	return file_filespacechain_filespacechain_file_entry_proto_rawDescData
}

var file_filespacechain_filespacechain_file_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_filespacechain_filespacechain_file_entry_proto_goTypes = []interface{}{
	(*FileEntry)(nil), // 0: filespacechain.filespacechain.FileEntry
}
var file_filespacechain_filespacechain_file_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filespacechain_filespacechain_file_entry_proto_init() }
func file_filespacechain_filespacechain_file_entry_proto_init() {
	if File_filespacechain_filespacechain_file_entry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filespacechain_filespacechain_file_entry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filespacechain_filespacechain_file_entry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filespacechain_filespacechain_file_entry_proto_goTypes,
		DependencyIndexes: file_filespacechain_filespacechain_file_entry_proto_depIdxs,
		MessageInfos:      file_filespacechain_filespacechain_file_entry_proto_msgTypes,
	}.Build()
	File_filespacechain_filespacechain_file_entry_proto = out.File
	file_filespacechain_filespacechain_file_entry_proto_rawDesc = nil
	file_filespacechain_filespacechain_file_entry_proto_goTypes = nil
	file_filespacechain_filespacechain_file_entry_proto_depIdxs = nil
}
