// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package filespacechain

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_GenesisState_2_list)(nil)

type _GenesisState_2_list struct {
	list *[]*FileEntry
}

func (x *_GenesisState_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_GenesisState_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_GenesisState_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*FileEntry)
	(*x.list)[i] = concreteValue
}

func (x *_GenesisState_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*FileEntry)
	*x.list = append(*x.list, concreteValue)
}

func (x *_GenesisState_2_list) AppendMutable() protoreflect.Value {
	v := new(FileEntry)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_2_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_GenesisState_2_list) NewElement() protoreflect.Value {
	v := new(FileEntry)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_2_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_GenesisState_4_list)(nil)

type _GenesisState_4_list struct {
	list *[]*HostingInquiry
}

func (x *_GenesisState_4_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_GenesisState_4_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_GenesisState_4_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*HostingInquiry)
	(*x.list)[i] = concreteValue
}

func (x *_GenesisState_4_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*HostingInquiry)
	*x.list = append(*x.list, concreteValue)
}

func (x *_GenesisState_4_list) AppendMutable() protoreflect.Value {
	v := new(HostingInquiry)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_4_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_GenesisState_4_list) NewElement() protoreflect.Value {
	v := new(HostingInquiry)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_4_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_GenesisState_6_list)(nil)

type _GenesisState_6_list struct {
	list *[]*HostingContract
}

func (x *_GenesisState_6_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_GenesisState_6_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_GenesisState_6_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*HostingContract)
	(*x.list)[i] = concreteValue
}

func (x *_GenesisState_6_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*HostingContract)
	*x.list = append(*x.list, concreteValue)
}

func (x *_GenesisState_6_list) AppendMutable() protoreflect.Value {
	v := new(HostingContract)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_6_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_GenesisState_6_list) NewElement() protoreflect.Value {
	v := new(HostingContract)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_6_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_GenesisState_8_list)(nil)

type _GenesisState_8_list struct {
	list *[]*HostingOffer
}

func (x *_GenesisState_8_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_GenesisState_8_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_GenesisState_8_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*HostingOffer)
	(*x.list)[i] = concreteValue
}

func (x *_GenesisState_8_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*HostingOffer)
	*x.list = append(*x.list, concreteValue)
}

func (x *_GenesisState_8_list) AppendMutable() protoreflect.Value {
	v := new(HostingOffer)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_8_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_GenesisState_8_list) NewElement() protoreflect.Value {
	v := new(HostingOffer)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_GenesisState_8_list) IsValid() bool {
	return x.list != nil
}

var (
	md_GenesisState                      protoreflect.MessageDescriptor
	fd_GenesisState_params               protoreflect.FieldDescriptor
	fd_GenesisState_fileEntryList        protoreflect.FieldDescriptor
	fd_GenesisState_fileEntryCount       protoreflect.FieldDescriptor
	fd_GenesisState_hostingInquiryList   protoreflect.FieldDescriptor
	fd_GenesisState_hostingInquiryCount  protoreflect.FieldDescriptor
	fd_GenesisState_hostingContractList  protoreflect.FieldDescriptor
	fd_GenesisState_hostingContractCount protoreflect.FieldDescriptor
	fd_GenesisState_hostingOfferList     protoreflect.FieldDescriptor
	fd_GenesisState_hostingOfferCount    protoreflect.FieldDescriptor
)

func init() {
	file_filespacechain_filespacechain_genesis_proto_init()
	md_GenesisState = File_filespacechain_filespacechain_genesis_proto.Messages().ByName("GenesisState")
	fd_GenesisState_params = md_GenesisState.Fields().ByName("params")
	fd_GenesisState_fileEntryList = md_GenesisState.Fields().ByName("fileEntryList")
	fd_GenesisState_fileEntryCount = md_GenesisState.Fields().ByName("fileEntryCount")
	fd_GenesisState_hostingInquiryList = md_GenesisState.Fields().ByName("hostingInquiryList")
	fd_GenesisState_hostingInquiryCount = md_GenesisState.Fields().ByName("hostingInquiryCount")
	fd_GenesisState_hostingContractList = md_GenesisState.Fields().ByName("hostingContractList")
	fd_GenesisState_hostingContractCount = md_GenesisState.Fields().ByName("hostingContractCount")
	fd_GenesisState_hostingOfferList = md_GenesisState.Fields().ByName("hostingOfferList")
	fd_GenesisState_hostingOfferCount = md_GenesisState.Fields().ByName("hostingOfferCount")
}

var _ protoreflect.Message = (*fastReflection_GenesisState)(nil)

type fastReflection_GenesisState GenesisState

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	return (*fastReflection_GenesisState)(x)
}

func (x *GenesisState) slowProtoReflect() protoreflect.Message {
	mi := &file_filespacechain_filespacechain_genesis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_GenesisState_messageType fastReflection_GenesisState_messageType
var _ protoreflect.MessageType = fastReflection_GenesisState_messageType{}

type fastReflection_GenesisState_messageType struct{}

func (x fastReflection_GenesisState_messageType) Zero() protoreflect.Message {
	return (*fastReflection_GenesisState)(nil)
}
func (x fastReflection_GenesisState_messageType) New() protoreflect.Message {
	return new(fastReflection_GenesisState)
}
func (x fastReflection_GenesisState_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_GenesisState
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_GenesisState) Descriptor() protoreflect.MessageDescriptor {
	return md_GenesisState
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_GenesisState) Type() protoreflect.MessageType {
	return _fastReflection_GenesisState_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_GenesisState) New() protoreflect.Message {
	return new(fastReflection_GenesisState)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_GenesisState) Interface() protoreflect.ProtoMessage {
	return (*GenesisState)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_GenesisState) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Params != nil {
		value := protoreflect.ValueOfMessage(x.Params.ProtoReflect())
		if !f(fd_GenesisState_params, value) {
			return
		}
	}
	if len(x.FileEntryList) != 0 {
		value := protoreflect.ValueOfList(&_GenesisState_2_list{list: &x.FileEntryList})
		if !f(fd_GenesisState_fileEntryList, value) {
			return
		}
	}
	if x.FileEntryCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.FileEntryCount)
		if !f(fd_GenesisState_fileEntryCount, value) {
			return
		}
	}
	if len(x.HostingInquiryList) != 0 {
		value := protoreflect.ValueOfList(&_GenesisState_4_list{list: &x.HostingInquiryList})
		if !f(fd_GenesisState_hostingInquiryList, value) {
			return
		}
	}
	if x.HostingInquiryCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.HostingInquiryCount)
		if !f(fd_GenesisState_hostingInquiryCount, value) {
			return
		}
	}
	if len(x.HostingContractList) != 0 {
		value := protoreflect.ValueOfList(&_GenesisState_6_list{list: &x.HostingContractList})
		if !f(fd_GenesisState_hostingContractList, value) {
			return
		}
	}
	if x.HostingContractCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.HostingContractCount)
		if !f(fd_GenesisState_hostingContractCount, value) {
			return
		}
	}
	if len(x.HostingOfferList) != 0 {
		value := protoreflect.ValueOfList(&_GenesisState_8_list{list: &x.HostingOfferList})
		if !f(fd_GenesisState_hostingOfferList, value) {
			return
		}
	}
	if x.HostingOfferCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.HostingOfferCount)
		if !f(fd_GenesisState_hostingOfferCount, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_GenesisState) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "filespacechain.filespacechain.GenesisState.params":
		return x.Params != nil
	case "filespacechain.filespacechain.GenesisState.fileEntryList":
		return len(x.FileEntryList) != 0
	case "filespacechain.filespacechain.GenesisState.fileEntryCount":
		return x.FileEntryCount != uint64(0)
	case "filespacechain.filespacechain.GenesisState.hostingInquiryList":
		return len(x.HostingInquiryList) != 0
	case "filespacechain.filespacechain.GenesisState.hostingInquiryCount":
		return x.HostingInquiryCount != uint64(0)
	case "filespacechain.filespacechain.GenesisState.hostingContractList":
		return len(x.HostingContractList) != 0
	case "filespacechain.filespacechain.GenesisState.hostingContractCount":
		return x.HostingContractCount != uint64(0)
	case "filespacechain.filespacechain.GenesisState.hostingOfferList":
		return len(x.HostingOfferList) != 0
	case "filespacechain.filespacechain.GenesisState.hostingOfferCount":
		return x.HostingOfferCount != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.GenesisState"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "filespacechain.filespacechain.GenesisState.params":
		x.Params = nil
	case "filespacechain.filespacechain.GenesisState.fileEntryList":
		x.FileEntryList = nil
	case "filespacechain.filespacechain.GenesisState.fileEntryCount":
		x.FileEntryCount = uint64(0)
	case "filespacechain.filespacechain.GenesisState.hostingInquiryList":
		x.HostingInquiryList = nil
	case "filespacechain.filespacechain.GenesisState.hostingInquiryCount":
		x.HostingInquiryCount = uint64(0)
	case "filespacechain.filespacechain.GenesisState.hostingContractList":
		x.HostingContractList = nil
	case "filespacechain.filespacechain.GenesisState.hostingContractCount":
		x.HostingContractCount = uint64(0)
	case "filespacechain.filespacechain.GenesisState.hostingOfferList":
		x.HostingOfferList = nil
	case "filespacechain.filespacechain.GenesisState.hostingOfferCount":
		x.HostingOfferCount = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.GenesisState"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_GenesisState) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "filespacechain.filespacechain.GenesisState.params":
		value := x.Params
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "filespacechain.filespacechain.GenesisState.fileEntryList":
		if len(x.FileEntryList) == 0 {
			return protoreflect.ValueOfList(&_GenesisState_2_list{})
		}
		listValue := &_GenesisState_2_list{list: &x.FileEntryList}
		return protoreflect.ValueOfList(listValue)
	case "filespacechain.filespacechain.GenesisState.fileEntryCount":
		value := x.FileEntryCount
		return protoreflect.ValueOfUint64(value)
	case "filespacechain.filespacechain.GenesisState.hostingInquiryList":
		if len(x.HostingInquiryList) == 0 {
			return protoreflect.ValueOfList(&_GenesisState_4_list{})
		}
		listValue := &_GenesisState_4_list{list: &x.HostingInquiryList}
		return protoreflect.ValueOfList(listValue)
	case "filespacechain.filespacechain.GenesisState.hostingInquiryCount":
		value := x.HostingInquiryCount
		return protoreflect.ValueOfUint64(value)
	case "filespacechain.filespacechain.GenesisState.hostingContractList":
		if len(x.HostingContractList) == 0 {
			return protoreflect.ValueOfList(&_GenesisState_6_list{})
		}
		listValue := &_GenesisState_6_list{list: &x.HostingContractList}
		return protoreflect.ValueOfList(listValue)
	case "filespacechain.filespacechain.GenesisState.hostingContractCount":
		value := x.HostingContractCount
		return protoreflect.ValueOfUint64(value)
	case "filespacechain.filespacechain.GenesisState.hostingOfferList":
		if len(x.HostingOfferList) == 0 {
			return protoreflect.ValueOfList(&_GenesisState_8_list{})
		}
		listValue := &_GenesisState_8_list{list: &x.HostingOfferList}
		return protoreflect.ValueOfList(listValue)
	case "filespacechain.filespacechain.GenesisState.hostingOfferCount":
		value := x.HostingOfferCount
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.GenesisState"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.GenesisState does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "filespacechain.filespacechain.GenesisState.params":
		x.Params = value.Message().Interface().(*Params)
	case "filespacechain.filespacechain.GenesisState.fileEntryList":
		lv := value.List()
		clv := lv.(*_GenesisState_2_list)
		x.FileEntryList = *clv.list
	case "filespacechain.filespacechain.GenesisState.fileEntryCount":
		x.FileEntryCount = value.Uint()
	case "filespacechain.filespacechain.GenesisState.hostingInquiryList":
		lv := value.List()
		clv := lv.(*_GenesisState_4_list)
		x.HostingInquiryList = *clv.list
	case "filespacechain.filespacechain.GenesisState.hostingInquiryCount":
		x.HostingInquiryCount = value.Uint()
	case "filespacechain.filespacechain.GenesisState.hostingContractList":
		lv := value.List()
		clv := lv.(*_GenesisState_6_list)
		x.HostingContractList = *clv.list
	case "filespacechain.filespacechain.GenesisState.hostingContractCount":
		x.HostingContractCount = value.Uint()
	case "filespacechain.filespacechain.GenesisState.hostingOfferList":
		lv := value.List()
		clv := lv.(*_GenesisState_8_list)
		x.HostingOfferList = *clv.list
	case "filespacechain.filespacechain.GenesisState.hostingOfferCount":
		x.HostingOfferCount = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.GenesisState"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.GenesisState does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "filespacechain.filespacechain.GenesisState.params":
		if x.Params == nil {
			x.Params = new(Params)
		}
		return protoreflect.ValueOfMessage(x.Params.ProtoReflect())
	case "filespacechain.filespacechain.GenesisState.fileEntryList":
		if x.FileEntryList == nil {
			x.FileEntryList = []*FileEntry{}
		}
		value := &_GenesisState_2_list{list: &x.FileEntryList}
		return protoreflect.ValueOfList(value)
	case "filespacechain.filespacechain.GenesisState.hostingInquiryList":
		if x.HostingInquiryList == nil {
			x.HostingInquiryList = []*HostingInquiry{}
		}
		value := &_GenesisState_4_list{list: &x.HostingInquiryList}
		return protoreflect.ValueOfList(value)
	case "filespacechain.filespacechain.GenesisState.hostingContractList":
		if x.HostingContractList == nil {
			x.HostingContractList = []*HostingContract{}
		}
		value := &_GenesisState_6_list{list: &x.HostingContractList}
		return protoreflect.ValueOfList(value)
	case "filespacechain.filespacechain.GenesisState.hostingOfferList":
		if x.HostingOfferList == nil {
			x.HostingOfferList = []*HostingOffer{}
		}
		value := &_GenesisState_8_list{list: &x.HostingOfferList}
		return protoreflect.ValueOfList(value)
	case "filespacechain.filespacechain.GenesisState.fileEntryCount":
		panic(fmt.Errorf("field fileEntryCount of message filespacechain.filespacechain.GenesisState is not mutable"))
	case "filespacechain.filespacechain.GenesisState.hostingInquiryCount":
		panic(fmt.Errorf("field hostingInquiryCount of message filespacechain.filespacechain.GenesisState is not mutable"))
	case "filespacechain.filespacechain.GenesisState.hostingContractCount":
		panic(fmt.Errorf("field hostingContractCount of message filespacechain.filespacechain.GenesisState is not mutable"))
	case "filespacechain.filespacechain.GenesisState.hostingOfferCount":
		panic(fmt.Errorf("field hostingOfferCount of message filespacechain.filespacechain.GenesisState is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.GenesisState"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.GenesisState does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_GenesisState) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "filespacechain.filespacechain.GenesisState.params":
		m := new(Params)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "filespacechain.filespacechain.GenesisState.fileEntryList":
		list := []*FileEntry{}
		return protoreflect.ValueOfList(&_GenesisState_2_list{list: &list})
	case "filespacechain.filespacechain.GenesisState.fileEntryCount":
		return protoreflect.ValueOfUint64(uint64(0))
	case "filespacechain.filespacechain.GenesisState.hostingInquiryList":
		list := []*HostingInquiry{}
		return protoreflect.ValueOfList(&_GenesisState_4_list{list: &list})
	case "filespacechain.filespacechain.GenesisState.hostingInquiryCount":
		return protoreflect.ValueOfUint64(uint64(0))
	case "filespacechain.filespacechain.GenesisState.hostingContractList":
		list := []*HostingContract{}
		return protoreflect.ValueOfList(&_GenesisState_6_list{list: &list})
	case "filespacechain.filespacechain.GenesisState.hostingContractCount":
		return protoreflect.ValueOfUint64(uint64(0))
	case "filespacechain.filespacechain.GenesisState.hostingOfferList":
		list := []*HostingOffer{}
		return protoreflect.ValueOfList(&_GenesisState_8_list{list: &list})
	case "filespacechain.filespacechain.GenesisState.hostingOfferCount":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: filespacechain.filespacechain.GenesisState"))
		}
		panic(fmt.Errorf("message filespacechain.filespacechain.GenesisState does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_GenesisState) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in filespacechain.filespacechain.GenesisState", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_GenesisState) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_GenesisState) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_GenesisState) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_GenesisState) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Params != nil {
			l = options.Size(x.Params)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.FileEntryList) > 0 {
			for _, e := range x.FileEntryList {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.FileEntryCount != 0 {
			n += 1 + runtime.Sov(uint64(x.FileEntryCount))
		}
		if len(x.HostingInquiryList) > 0 {
			for _, e := range x.HostingInquiryList {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.HostingInquiryCount != 0 {
			n += 1 + runtime.Sov(uint64(x.HostingInquiryCount))
		}
		if len(x.HostingContractList) > 0 {
			for _, e := range x.HostingContractList {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.HostingContractCount != 0 {
			n += 1 + runtime.Sov(uint64(x.HostingContractCount))
		}
		if len(x.HostingOfferList) > 0 {
			for _, e := range x.HostingOfferList {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.HostingOfferCount != 0 {
			n += 1 + runtime.Sov(uint64(x.HostingOfferCount))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.HostingOfferCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.HostingOfferCount))
			i--
			dAtA[i] = 0x48
		}
		if len(x.HostingOfferList) > 0 {
			for iNdEx := len(x.HostingOfferList) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.HostingOfferList[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x42
			}
		}
		if x.HostingContractCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.HostingContractCount))
			i--
			dAtA[i] = 0x38
		}
		if len(x.HostingContractList) > 0 {
			for iNdEx := len(x.HostingContractList) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.HostingContractList[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x32
			}
		}
		if x.HostingInquiryCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.HostingInquiryCount))
			i--
			dAtA[i] = 0x28
		}
		if len(x.HostingInquiryList) > 0 {
			for iNdEx := len(x.HostingInquiryList) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.HostingInquiryList[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x22
			}
		}
		if x.FileEntryCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.FileEntryCount))
			i--
			dAtA[i] = 0x18
		}
		if len(x.FileEntryList) > 0 {
			for iNdEx := len(x.FileEntryList) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.FileEntryList[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x12
			}
		}
		if x.Params != nil {
			encoded, err := options.Marshal(x.Params)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*GenesisState)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Params == nil {
					x.Params = &Params{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Params); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FileEntryList", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.FileEntryList = append(x.FileEntryList, &FileEntry{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.FileEntryList[len(x.FileEntryList)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FileEntryCount", wireType)
				}
				x.FileEntryCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.FileEntryCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field HostingInquiryList", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.HostingInquiryList = append(x.HostingInquiryList, &HostingInquiry{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.HostingInquiryList[len(x.HostingInquiryList)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field HostingInquiryCount", wireType)
				}
				x.HostingInquiryCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.HostingInquiryCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field HostingContractList", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.HostingContractList = append(x.HostingContractList, &HostingContract{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.HostingContractList[len(x.HostingContractList)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field HostingContractCount", wireType)
				}
				x.HostingContractCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.HostingContractCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field HostingOfferList", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.HostingOfferList = append(x.HostingOfferList, &HostingOffer{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.HostingOfferList[len(x.HostingOfferList)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 9:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field HostingOfferCount", wireType)
				}
				x.HostingOfferCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.HostingOfferCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: filespacechain/filespacechain/genesis.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the filespacechain module's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// params defines all the parameters of the module.
	Params               *Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	FileEntryList        []*FileEntry       `protobuf:"bytes,2,rep,name=fileEntryList,proto3" json:"fileEntryList,omitempty"`
	FileEntryCount       uint64             `protobuf:"varint,3,opt,name=fileEntryCount,proto3" json:"fileEntryCount,omitempty"`
	HostingInquiryList   []*HostingInquiry  `protobuf:"bytes,4,rep,name=hostingInquiryList,proto3" json:"hostingInquiryList,omitempty"`
	HostingInquiryCount  uint64             `protobuf:"varint,5,opt,name=hostingInquiryCount,proto3" json:"hostingInquiryCount,omitempty"`
	HostingContractList  []*HostingContract `protobuf:"bytes,6,rep,name=hostingContractList,proto3" json:"hostingContractList,omitempty"`
	HostingContractCount uint64             `protobuf:"varint,7,opt,name=hostingContractCount,proto3" json:"hostingContractCount,omitempty"`
	HostingOfferList     []*HostingOffer    `protobuf:"bytes,8,rep,name=hostingOfferList,proto3" json:"hostingOfferList,omitempty"`
	HostingOfferCount    uint64             `protobuf:"varint,9,opt,name=hostingOfferCount,proto3" json:"hostingOfferCount,omitempty"`
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filespacechain_filespacechain_genesis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_filespacechain_filespacechain_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetFileEntryList() []*FileEntry {
	if x != nil {
		return x.FileEntryList
	}
	return nil
}

func (x *GenesisState) GetFileEntryCount() uint64 {
	if x != nil {
		return x.FileEntryCount
	}
	return 0
}

func (x *GenesisState) GetHostingInquiryList() []*HostingInquiry {
	if x != nil {
		return x.HostingInquiryList
	}
	return nil
}

func (x *GenesisState) GetHostingInquiryCount() uint64 {
	if x != nil {
		return x.HostingInquiryCount
	}
	return 0
}

func (x *GenesisState) GetHostingContractList() []*HostingContract {
	if x != nil {
		return x.HostingContractList
	}
	return nil
}

func (x *GenesisState) GetHostingContractCount() uint64 {
	if x != nil {
		return x.HostingContractCount
	}
	return 0
}

func (x *GenesisState) GetHostingOfferList() []*HostingOffer {
	if x != nil {
		return x.HostingOfferList
	}
	return nil
}

func (x *GenesisState) GetHostingOfferCount() uint64 {
	if x != nil {
		return x.HostingOfferCount
	}
	return 0
}

var File_filespacechain_filespacechain_genesis_proto protoreflect.FileDescriptor

var file_filespacechain_filespacechain_genesis_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f,
	0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x1a, 0x11, 0x61, 0x6d,
	0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2a, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x33, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x34, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x31, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x68, 0x6f, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x96, 0x05, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x48, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x09, 0xc8, 0xde, 0x1f, 0x00, 0xa8, 0xe7, 0xb0,
	0x2a, 0x01, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x54, 0x0a, 0x0d, 0x66, 0x69,
	0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x04, 0xc8, 0xde, 0x1f,
	0x00, 0x52, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x63, 0x0a, 0x12, 0x68, 0x6f, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x71, 0x75,
	0x69, 0x72, 0x79, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x12, 0x68, 0x6f, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a,
	0x13, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x68, 0x6f, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x66, 0x0a, 0x13, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x04, 0xc8, 0xde,
	0x1f, 0x00, 0x52, 0x13, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x14, 0x68, 0x6f, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x14, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x10, 0x68,
	0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x10, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x68, 0x6f,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x66,
	0x66, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0xf6, 0x01, 0x0a, 0x21, 0x63, 0x6f, 0x6d,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x0c,
	0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xa2, 0x02,
	0x03, 0x46, 0x46, 0x58, 0xaa, 0x02, 0x1d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0xca, 0x02, 0x1d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0xe2, 0x02, 0x29, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x1e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x3a, 0x3a, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filespacechain_filespacechain_genesis_proto_rawDescOnce sync.Once
	file_filespacechain_filespacechain_genesis_proto_rawDescData = file_filespacechain_filespacechain_genesis_proto_rawDesc
)

func file_filespacechain_filespacechain_genesis_proto_rawDescGZIP() []byte {
	file_filespacechain_filespacechain_genesis_proto_rawDescOnce.Do(func() {
		file_filespacechain_filespacechain_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(file_filespacechain_filespacechain_genesis_proto_rawDescData)
	})
	return file_filespacechain_filespacechain_genesis_proto_rawDescData
}

var file_filespacechain_filespacechain_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_filespacechain_filespacechain_genesis_proto_goTypes = []interface{}{
	(*GenesisState)(nil),    // 0: filespacechain.filespacechain.GenesisState
	(*Params)(nil),          // 1: filespacechain.filespacechain.Params
	(*FileEntry)(nil),       // 2: filespacechain.filespacechain.FileEntry
	(*HostingInquiry)(nil),  // 3: filespacechain.filespacechain.HostingInquiry
	(*HostingContract)(nil), // 4: filespacechain.filespacechain.HostingContract
	(*HostingOffer)(nil),    // 5: filespacechain.filespacechain.HostingOffer
}
var file_filespacechain_filespacechain_genesis_proto_depIdxs = []int32{
	1, // 0: filespacechain.filespacechain.GenesisState.params:type_name -> filespacechain.filespacechain.Params
	2, // 1: filespacechain.filespacechain.GenesisState.fileEntryList:type_name -> filespacechain.filespacechain.FileEntry
	3, // 2: filespacechain.filespacechain.GenesisState.hostingInquiryList:type_name -> filespacechain.filespacechain.HostingInquiry
	4, // 3: filespacechain.filespacechain.GenesisState.hostingContractList:type_name -> filespacechain.filespacechain.HostingContract
	5, // 4: filespacechain.filespacechain.GenesisState.hostingOfferList:type_name -> filespacechain.filespacechain.HostingOffer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_filespacechain_filespacechain_genesis_proto_init() }
func file_filespacechain_filespacechain_genesis_proto_init() {
	if File_filespacechain_filespacechain_genesis_proto != nil {
		return
	}
	file_filespacechain_filespacechain_params_proto_init()
	file_filespacechain_filespacechain_file_entry_proto_init()
	file_filespacechain_filespacechain_hosting_inquiry_proto_init()
	file_filespacechain_filespacechain_hosting_contract_proto_init()
	file_filespacechain_filespacechain_hosting_offer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_filespacechain_filespacechain_genesis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenesisState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filespacechain_filespacechain_genesis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filespacechain_filespacechain_genesis_proto_goTypes,
		DependencyIndexes: file_filespacechain_filespacechain_genesis_proto_depIdxs,
		MessageInfos:      file_filespacechain_filespacechain_genesis_proto_msgTypes,
	}.Build()
	File_filespacechain_filespacechain_genesis_proto = out.File
	file_filespacechain_filespacechain_genesis_proto_rawDesc = nil
	file_filespacechain_filespacechain_genesis_proto_goTypes = nil
	file_filespacechain_filespacechain_genesis_proto_depIdxs = nil
}
